### ISSUE TITLE
No newrelic-python-agent in pip?

### ISSUE THREAD

**Issue by priiiiit** [NewRelic-Python-Plugins/newrelic-python-agent#12]
```
$ pip install newrelic-python-agent
Collecting newrelic-python-agent
  Could not find a version that satisfies the requirement newrelic-python-agent (from versions: )
No matching distribution found for newrelic-python-agent
```
Am I missing something?

**Comment by wolph** [comment]
This project is pretty much a brand new fork of the newrelic-plugin-agent so you're just a tad too early. It's on the todo list though :)

**Comment by Rockstar04** [comment]
Ya, I still haven't submitted the new fork to Pypi yet. @WoLpH should I create a gmail all the maintainers can use to create a Pypi account instead of one of us using our personal emails?

**Comment by wolph** [comment]
No need, you can add multiple maintainers to a pypi project these days so you can add it through your own account and add extra roles.

**Comment by Rockstar04** [comment]
Excellent, I will get that all setup when I get into work tomorrow morning.

**Comment by Rockstar04** [comment]
@ppihus I just added the new repo to Pypi.  https://pypi.python.org/pypi/newrelic_python_agent

I'll close this issue, but if you still have issues installing it we can reopen.
