### ISSUE TITLE
Inaccurate Memcached connections count

### ISSUE THREAD

**Issue by BryanSD** [NewRelic-Python-Plugins/newrelic-python-agent#16]
The number of connections is inflated for this plugin. You can view the connection count in two places: 1) Under Plugins > Memcached (`https://rpm.newrelic.com/accounts/{id}/plugins/{id}`), or 2) In the bar along the bottom of the page when viewing a particular instance's metrics (`https://rpm.newrelic.com/accounts/{id}/dashboard/{id}`).

When performing `stats` via `telnet` to Memcached, I see the following information:

```
stats
...
STAT version 1.4.15
...
STAT curr_connections 10
...
```

For the above data, with the plugin running once every 60 seconds, it reports 40 active connections in New Relic. If the reporting frequency is increased to once every 30 seconds, New Relic reports 80 active connections.

The bar along the bottom (viewing option 2 above) seems to indicate the data is for the past 5 minutes, so perhaps something is being summed when it shouldn't. I'm not too familiar with how New Relic expects and processes these metrics, but I am comfortable with Python if someone would offer hints as to what needs to be changed.

I should also note the connection count _graph_ is correct, it's just this metric being displayed elsewhere that's off.

I imagine this is similar to https://github.com/MeetMe/newrelic-plugin-agent/issues/303 in the old repository.

**Comment by tjstansell** [comment]
I suspect this is actually a dashboard problem rather than a plugin metric problem.  The only way to fix this is to probably decide if we want to manage our own dashboards instead of using the old MeetMe ones.  So, this probably needs a decision on #15 on if we should manage our own dashboards.
