### ISSUE TITLE
Urllib issues

### ISSUE THREAD

**Issue by Bobspadger** [NewRelic-Python-Plugins/newrelic-python-agent#19]
`sudo newrelic-python-agent -c /etc/newrelic/newrelic-plugin-agent.cfg
/usr/local/lib/python2.7/dist-packages/requests/__init__.py:80: RequestsDependencyWarning: urllib3 (1.22) or chardet (2.0.1) doesn't match a supported version!
  RequestsDependencyWarning)`

This is running on ubuntu 14.04LTS

What I have done.

1. Upgrade Python to 2.7.14 (Due to SSL errors with pip not allowing me to install anything)
2. Checked my package versions using pip freeze

I've then chased my tail with various other witch hunts and got nowhere.

`Requirement already up-to-date: urllib3<1.23,>=1.21.1 in /usr/local/lib/python2.7/dist-packages (from requests>=2.0.0->newrelic-python-agent)
Requirement already up-to-date: idna<2.7,>=2.5 in /usr/local/lib/python2.7/dist-packages (from requests>=2.0.0->newrelic-python-agent)
Requirement already up-to-date: chardet<3.1.0,>=3.0.2 in /usr/local/lib/python2.7/dist-packages (from requests>=2.0.0->newrelic-python-agent)
Requirement already up-to-date: certifi>=2017.4.17 in /usr/local/lib/python2.7/dist-packages (from requests>=2.0.0->newrelic-python-agent)`

Any quick thoughts?

**Comment by wolph** [comment]
It appears to be a warning only so I'm guessing it can be ignored safely.

You could try updating all of these packages at the same time so pip calculates the dependencies:
```
pip install -U requests urllib3 chardet idna certifi
```

**Comment by Bobspadger** [comment]
It does appear to be sending data now (it took forever) and the logs were showing ssl errors 

I'll close this for now, but at least its been brought to your attention.
