### ISSUE TITLE
support dynamic configs

### ISSUE THREAD

**Issue by tjstansell** [NewRelic-Python-Plugins/newrelic-python-agent#22]
I have a need for dynamically generating plugin configs, and I have a proposed implementation.  The use case is to be able to use a mysql plugin to query AWS RDS instances to get detailed monitoring data.  As the set of RDS instances is likely to change over time, I would like a way to auto-determine the current set of RDS instances to monitor.  My implementation uses a new ConfigPlugin class to run as a separate thread along with the metric plugins.  The result is a config block to apply to the currently running application config.

I still need to add the necessary documentation changes, so I won't submit a PR quite yet, but you can take a look at my proposed changes at https://github.com/tjstansell/newrelic-python-agent/tree/dynamic_configs

I also have a new mysql plugin as well as a mysql-config that implements this.  Not sure how to handle that part, as it ties to #2 with the possible restructuring of the agent.

**Comment by Rockstar04** [comment]
Your fork looks really well though out and well documented. If you would like to open a pull for your mysql plugin there that would be greatly appreciated as well.

**Comment by tjstansell** [comment]
Well, right now my `dynamic_configs` branch is based on a `develop` branch i created that has PR #21  merged.  I can submit a PR for the mysql plugin separately, as it doesn't rely on any of these changes.  And I also have a mysql-config plugin that does rely on all of the `dynamic_configs` branch changes.  That could be included in `dynamic_configs` as an example use case or a separate PR could be included for that.  That said, I do still need to put some more documentation in places for those plugins... but that could always happen later.

How do folks handle PRs that rely on other PRs to land?  I don't have much experience dealing with this sort of stuff... most of what I do is simple check-ins to master. :)

**Comment by tjstansell** [comment]
OK.  I've rebased my changes based on the current master so that it doesn't technically require any of the other PRs I've submitted.  Though, as I mention in the PR, it's much more useful with PR #21 and PR #23 landed.

**Comment by Rockstar04** [comment]
Issue resolved in current master. Thanks @tjstansell for the contributions!

**Comment by tjstansell** [comment]
Groovy!
