### ISSUE TITLE
[couchdb] The plugin interface on newrelic is sparse

### ISSUE THREAD

**Issue by ktaragorn** [NewRelic-Python-Plugins/newrelic-python-agent#30]
While we seem to have access to and report quite a lot of info, the plugin dashboard shows quite limited data, is this expected? Do you guys have control over what is shown in the database or is it with the older organization?

Does this plugin mean that couchdb is supposed to show up as a database in our APM panels? Because this doesnt happen.

**Comment by ktaragorn** [comment]
Looking at their docs, i think we use stats from begining of time, shouldnt we instead look at last 1 minute or so? https://wiki.apache.org/couchdb/Runtime_Statistics

**Comment by ktaragorn** [comment]
Specifically we want to see `request_time` to track performance issues but i am not seeing it.

**Comment by ktaragorn** [comment]
might be tied to  #15

**Comment by wolph** [comment]
I'm not running couchdb myself so I can't easily verify, but the code does appear to gathering `request_time`: https://github.com/NewRelic-Python-Plugins/newrelic-python-agent/blob/master/newrelic_python_agent/plugins/couchdb.py#L48-L49

It should be called `Requests/Duration` within your newrelic interface.

Also, I think the fields are all based on the "current" data so it shouldn't be all time.

**Comment by ktaragorn** [comment]
I realize that, as I mention right at the top, we are collecting it but it doesnt seem to be shown on the dashboard. I only see it mentioned in the summary page (as 0) and the dashboard for this host has no mention of request time.

**Comment by ktaragorn** [comment]
> It should be called Requests/Duration within your newrelic interface.

I am not sure what to do with this. I dont use insights and I dont see any way to graph custom metrics or change the dashboard.

**Comment by ktaragorn** [comment]
> Current is a sum of the values recorded. For things like HTTP requests, this is the total number of requsts. 

This is from the documentation and thus i am confused. It does seem to work though, not exactly sure how.

**Comment by wolph** [comment]
Ah, I missed that part. In that case it might need to be changed in the plugin configuration panel.

Since I don't have a couchdb installation to test with right now I can't take care of that, but for the time being you can easily do it yourself. Simply modify the GUID to something else and after that you can add the new metrics: https://docs.newrelic.com/docs/plugins/developing-plugins/structuring-your-plugin/creating-summary-metrics-plugins

**Comment by wolph** [comment]
The explanation in their docs isn't too clear, I read it as "current value this second" but I might be wrong...

> Each metric is aggregated over four periods time. In the default output of /_stats the period of time is since CouchDB was started. The **aggregate values are calculated on a per-second basis**. So values {httpd, requests} will include the number of requests made against the HTTP API per second since CouchDB was started. **current is the current value**, the number of requests. max and min are the respective extreme values and mean is arithmetic mean value for the period of time with a standard deviation of steddev. description is a human-readable description of the metric and count is the number of times this metric was counted.
