### ISSUE TITLE
NPI compatibility?

### ISSUE THREAD

**Issue by wolph** [NewRelic-Python-Plugins/newrelic-python-agent#4]
It might be nice to make the plugin NPI-compatible in the future, it could make installing it a bit more straightforward for people: https://docs.newrelic.com/docs/plugins/plugins-new-relic/installing-plugins/installing-npi-compatible-plugin

**Comment by Rockstar04** [comment]
It looks like plugins HAVE to be either a .jar (Java) or .exe (.NET) plugin to be NPI compatible. The main reason I'm trying to get this project up and running is to avoid java at all costs. Most Linux systems have python installed already, so a simple copy and paste from a user guide shouldn't be to challenging.  I would say python 2.7 and python 3.0+ support would be more important as newer distros start shipping python 3 as their default.

**Comment by wolph** [comment]
It seems you're right: https://docs.newrelic.com/docs/plugins/developing-plugins/sharing-your-plugin/using-new-relic-platform-installer-npi-utility#requirements

That makes it unpractical at best, guess we'll remove that option :)
