### ISSUE TITLE
New Relic has killed Plugins

### ISSUE THREAD

**Issue by tjstansell** [NewRelic-Python-Plugins/newrelic-python-agent#46]
This codebase has become obsolete since New Relic is killing Plugins.  This repo should just get archived.
https://discuss.newrelic.com/t/new-relic-plugin-eol-wednesday-june-16th-2021/127267

**Comment by wolph** [comment]
Honestly, they nerfed the free version enough that I stopped using it a while ago

**Comment by Rockstar04** [comment]
Thanks for the update @tjstansell
