### ISSUE TITLE
Python 2 / 3 Support

### ISSUE THREAD

**Issue by Rockstar04** [NewRelic-Python-Plugins/newrelic-python-agent#5]
With some newer distros defaulting to python 3.x (Fedora 23+, Ubuntu 18.04) we should look to support Python 2 and 3. RHEL 6 seems to have the oldest default version of Python at 2.6.

Note to self for future reference: https://github.com/benjaminp/six

**Comment by Rockstar04** [comment]
| Distro        | Version | Codename  | Python Default | Python 3 | Python 2 | End of Support              | 
|---------------|---------|-----------|----------------|----------|----------|-----------------------------| 
| Ubuntu        | 18.04   | TBD       | 3.x.x          | 3.x.x    | 2.7.x    |                             | 
| Ubuntu        | 17.04   | zesty     | 2.7.13         | 3.5.3    | 2.7.13   |                             | 
| Ubuntu        | 16.04   | xenial    | 2.7.11         | 3.5.1    | 2.7.11   |                             | 
| Ubuntu        | 14.04   | trusty    | 2.7.5          | 3.4.0    | 2.7.5    |                             | 
| Ubuntu        | 12.04   | precise   | 2.7.2          | 3.2.3    | 2.7.2    |                             | 
| Debian        | 9       | stretch   | 2.7.13         | 3.5      | 2.7.13   |                             | 
| Debian        | 8       | jessie    | 2.7.9          | 3.4      | 2.7.9    |                             | 
| Debian        | 7       | wheezy    | 2.7.3          | 3.2      | 2.7.3    |                             | 
| Linux Mint    | 18      | sarah     | 2.7.11         | 3.5      | 2.7.11   |                             | 
| Linux Mint    | 17      | rosa      | 2.7.6          | 3.4      | 2.7.6    |                             | 
| Linux Mint    | 13      | maya      | 2.7.3          | 3.2      | 2.7.3    |                             | 
| Fedora        | 25      |           | 3.5.2          | 3.5.2    | 2.7      |                             | 
| Fedora        | 24      |           | 3.5.1          | 3.5.1    | 2.7      |                             | 
| Fedora        | 23      |           | 3.4.3          | 3.4.3    | 2.7      |                             | 
| Fedora        | 22      |           | 2.7.9          | 3.4      | 2.7.9    |                             | 
| RHEL          | 7       | maipo     |                | -        | 2.7      |                             | 
| RHEL          | 6       | santiago  |                | -        | 2.6      | "Monday, November 30, 2020" | 
| RHEL          | 5       | tikanga   |                | -        | 2.4      | "Friday, March 31, 2017"    | 
| OpenSUSE      | 42.1    | malachite |                | 3.4      | 2.7      |                             | 
| OpenSUSE      | 13.2    | harlequin |                | 3.4      | 2.7      |                             | 
| CentOS        | 7       |           |                | -        | 2.7      |                             | 
| CentOS        | 6       |           |                | -        | 2.6      | "Monday, November 30, 2020" | 
| CentOS        | 5       |           |                | -        | 2.4      | "Friday, March 31, 2017"    | 
| Elementary OS | 0.4     | loki      |                | 3.5      | 2.7      |                             | 
| Elementary OS | 0.3     | freya     |                | 3.4      | 2.7      |                             |

**Comment by wolph** [comment]
Python 2.6 might be a bit of a problem... it's not impossible to code for it but it's becoming harder to test since many (testing) libraries are dropping support. That's why I've dropped Python 2.6 support from many of my libraries, it's become hard to maintain even though it probably still works.

**Comment by Rockstar04** [comment]
From the reading I've done, it will suck. How about we continue 2.6 support for this repository, and then start from scratch with python 3 support with the modular repositories as mentioned in #2 ?

**Comment by wolph** [comment]
Sounds like a plan :)

We can still keep Python 2.6 support without too much effort, the most notable difference will be in the [collections](https://docs.python.org/2.7/library/collections.html#module-collections) module (no `OrderedDict` for Python 2.6) and the lacking of the [argparse](https://docs.python.org/2.7/library/argparse.html#module-argparse) module. Both of which have Python 2.6 backports so they can be circumvented by installing some extra packages.

Beyond that we need to stay away from things such as dict comprehensions, set literals and multiple context managers in a single statement. Especially the last one might be useful for this project but it's easy enough to work around.

The only thing that's really annoying is testing it and making sure it keeps working...

**Comment by hugovk** [comment]
> The only thing that's really annoying is testing it and making sure it keeps working...

For that reason alone I wouldn't bother with Python 2.6. It's 4 years without security updates, little used, RHEL 6 can upgrade Python using SCL or pin an old version, and as you've discovered many Python libraries have already dropped it.

Here's the pip installs for newrelic-python-agent from PyPI for the last month (via `pypinfo --percent --pip newrelic-python-agent pyversion`)

| python_version | percent | download_count |
| -------------- | ------: | -------------: |
| 2.7            |  100.0% |            109 |

**Comment by wolph** [comment]
Agreed, for people still stuck at 2.6 we can simply offer an old/legacy download which won't receive updates anymore.
